In [1]:
import numpy as np

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array = np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

40

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.random.random(5)

array([0.53281962, 0.87431426, 0.74133071, 0.42961823, 0.89371696])

In [11]:
# array arithmetic

In [12]:
my_list1 = [1,2]

In [13]:
my_list2 = [2,3]

In [14]:
my_list1 + my_list2

[1, 2, 2, 3]

In [15]:
my_numpy_array1 = np.array(my_list1)

In [16]:
my_numpy_array2 = np.array(my_list2)

In [17]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [18]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [19]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [20]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [21]:
my_numpy_array1

array([1, 2])

In [22]:
my_numpy_array1 * 5

array([ 5, 10])

In [23]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [26]:
other_array = np.array([10,20,30,40,50])

In [27]:
other_array.min()

10

In [28]:
other_array.sum()

150

In [29]:
#arange & indexing

In [30]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np_array = np.arange(0,10)

In [34]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np_array[0]

0

In [36]:
np_array[-1]

9

In [37]:
np_array[1:4:]

array([1, 2, 3])

In [38]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
np_array[2:6:2]

array([2, 4])

In [40]:
#random

In [41]:
np.random.randn(4)

array([-0.05088203, -0.61757118, -1.13441811,  0.97426217])

In [42]:
np.random.randn(4,4)

array([[ 0.27485085, -0.50309885, -0.79922906, -0.10707047],
       [ 0.24684001,  0.13412663, -0.22474363,  2.10601913],
       [ 0.65595813, -0.37954299, -0.56720123,  1.47763602],
       [-0.88776663,  0.44117339,  0.73919486,  1.8844032 ]])

In [43]:
np.random.randint(1,300,5)

array([227, 130, 223, 154, 183])