In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][1]

10

In [6]:
# row * column

In [7]:
numpy_matrix = np.array([[5,10],[15,20]])

In [8]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [9]:
numpy_matrix[1][0]

15

In [10]:
numpy_matrix.sum()

50

In [11]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.random.random((3,2))

array([[0.16798959, 0.57679557],
       [0.92649835, 0.72529421],
       [0.64799579, 0.176546  ]])

In [15]:
# matrix arithmetic

In [16]:
first_array = np.array([[10,20],[30,40]])

In [17]:
second_array = np.array([[5,15],[25,35]])

In [18]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [19]:
first_array

array([[10, 20],
       [30, 40]])

In [20]:
third_array = np.array([[50,60]])

In [21]:
third_array

array([[50, 60]])

In [22]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [23]:
fourth_array = np.array([[10,20,30,40,50]])

In [24]:
#first_array + fourth_array

In [25]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [26]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [27]:
third_array = np.array([[10],[20]])

In [28]:
third_array

array([[10],
       [20]])

In [29]:
third_array.shape

(2, 1)

In [30]:
first_array.shape

(2, 2)

In [31]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [32]:
first_array

array([[10, 20],
       [30, 40]])

In [33]:
# matrix multiplication

In [34]:
first_array

array([[10, 20],
       [30, 40]])

In [35]:
second_array

array([[ 5, 15],
       [25, 35]])

In [36]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [37]:
first_matrix = np.array([[10,20,30]])

In [38]:
first_matrix

array([[10, 20, 30]])

In [39]:
first_matrix.shape

(1, 3)

In [40]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [41]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [42]:
second_matrix.shape

(3, 2)

In [43]:
result_matrix = first_matrix.dot(second_matrix)

In [44]:
result_matrix

array([[120, 180]])

In [45]:
result_matrix.shape

(1, 2)