In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([30, 22, 86, 15, 52,  8,  8, 71, 89, 72,  4, 75, 94, 67, 34, 43, 33,
       92, 39, 46])

In [4]:
new_array > 25

array([ True, False,  True, False,  True, False, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
new_array[new_array > 25]

array([30, 86, 52, 71, 89, 72, 75, 94, 67, 34, 43, 33, 92, 39, 46])

In [6]:
new_array[new_array < 25]

array([22, 15,  8,  8,  4])

In [7]:
# transpose & reshape

In [8]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [9]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [10]:
matrix_array.shape

(3, 2)

In [11]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
random_array = np.random.random((6,1))

In [14]:
random_array

array([[0.80941836],
       [0.07833741],
       [0.93315867],
       [0.12167883],
       [0.16201643],
       [0.27716129]])

In [15]:
random_array.shape

(6, 1)

In [16]:
random_array.reshape(2,3)

array([[0.80941836, 0.07833741, 0.93315867],
       [0.12167883, 0.16201643, 0.27716129]])

In [17]:
random_array.reshape(3,2)

array([[0.80941836, 0.07833741],
       [0.93315867, 0.12167883],
       [0.16201643, 0.27716129]])

In [18]:
# z-score

In [20]:
data = np.array([10,12,13,15,18,25,100,105])

In [21]:
# outlier

In [22]:
mean = np.mean(data)

In [23]:
mean

37.25

In [24]:
data.sum() / len(data)

37.25

In [25]:
std = np.std(data)

In [26]:
std

37.9333296719389

In [27]:
z_scores = (data - mean) / std

In [28]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [30]:
data[z_scores > 1]

array([100, 105])

In [31]:
# math equations

In [32]:
# 2x + 3y = 8 and 5x + 7y = 19

In [33]:
#coefficient

In [34]:
A = np.array([[2,3],[5,7]])

In [35]:
#constant

In [36]:
b = np.array([8,19])

In [37]:
solution = np.linalg.solve(A,b)

In [38]:
solution

array([1., 2.])